spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

aws:
  sqs:
    region: eu-west-2
    accesskey: ${ACCESS_KEY}
    secretkey: ${SECRET_KEY}
    queue:
      link: crime-apps-dev-create-link-queue-m
      unlink: crime-apps-dev-unlink-queue-m