server:
  port : 8090
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

cloud-platform:
  aws:
    sqs:
      region: ${CLOUD_PLATFORM_QUEUE_REGION}
      accesskey: ${CLOUD_PLATFORM_QUEUE_ACCESS_KEY}
      secretkey: ${CLOUD_PLATFORM_QUEUE_SECRET_KEY}
      queue:
        link: ${CREATE_LINK_QUEUE}
        unlink: ${UNLINK_QUEUE}
        laaStatus: ${LAA_STATUS_UPDATE_QUEUE}
        hearingResulted: ${HEARING_RESULTED_QUEUE}

cda:
  oauth:
    url: ${CDA_OAUTH_URL}
    clientId: ${CDA_OAUTH_CLIENT_ID}
    clientSecret: ${CDA_OAUTH_CLIENT_SECRET}
  laastatus:
    url: ${CDA_LAA_STATUS_URL}