version: "3.2"

services:
  app:
    build:
      context: .
    environment:
    - DATASOURCE_URL=jdbc:oracle:thin:@host.docker.internal:1521:maatdb
    - DATASOURCE_USERNAME=mla
    ports:
    - 8090:8090
    - 8091:8091
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8091 -jar app.jar